# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kevin-sosa/work/etc/micmac

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kevin-sosa/work/etc/micmac

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin-sosa/work/etc/micmac/CMakeFiles /home/kevin-sosa/work/etc/micmac//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kevin-sosa/work/etc/micmac/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ANN

# Build rule for target.
ANN: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ANN
.PHONY : ANN

# fast build rule for target.
ANN/fast:
	$(MAKE) $(MAKESILENT) -f CodeExterne/ANN/CMakeFiles/ANN.dir/build.make CodeExterne/ANN/CMakeFiles/ANN.dir/build
.PHONY : ANN/fast

#=============================================================================
# Target rules for targets named poisson

# Build rule for target.
poisson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 poisson
.PHONY : poisson

# fast build rule for target.
poisson/fast:
	$(MAKE) $(MAKESILENT) -f CodeExterne/Poisson/CMakeFiles/poisson.dir/build.make CodeExterne/Poisson/CMakeFiles/poisson.dir/build
.PHONY : poisson/fast

#=============================================================================
# Target rules for targets named PoissonRecon

# Build rule for target.
PoissonRecon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PoissonRecon
.PHONY : PoissonRecon

# fast build rule for target.
PoissonRecon/fast:
	$(MAKE) $(MAKESILENT) -f CodeExterne/Poisson/CMakeFiles/PoissonRecon.dir/build.make CodeExterne/Poisson/CMakeFiles/PoissonRecon.dir/build
.PHONY : PoissonRecon/fast

#=============================================================================
# Target rules for targets named SurfaceTrimmer

# Build rule for target.
SurfaceTrimmer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SurfaceTrimmer
.PHONY : SurfaceTrimmer

# fast build rule for target.
SurfaceTrimmer/fast:
	$(MAKE) $(MAKESILENT) -f CodeExterne/Poisson/CMakeFiles/SurfaceTrimmer.dir/build.make CodeExterne/Poisson/CMakeFiles/SurfaceTrimmer.dir/build
.PHONY : SurfaceTrimmer/fast

#=============================================================================
# Target rules for targets named elise

# Build rule for target.
elise: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elise
.PHONY : elise

# fast build rule for target.
elise/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/elise.dir/build.make src/CMakeFiles/elise.dir/build
.PHONY : elise/fast

#=============================================================================
# Target rules for targets named elise_

# Build rule for target.
elise_: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elise_
.PHONY : elise_

# fast build rule for target.
elise_/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/elise_.dir/build.make src/CMakeFiles/elise_.dir/build
.PHONY : elise_/fast

#=============================================================================
# Target rules for targets named mm3d

# Build rule for target.
mm3d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mm3d
.PHONY : mm3d

# fast build rule for target.
mm3d/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/mm3d.dir/build.make src/CBinaires/CMakeFiles/mm3d.dir/build
.PHONY : mm3d/fast

#=============================================================================
# Target rules for targets named AperiCloud

# Build rule for target.
AperiCloud: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AperiCloud
.PHONY : AperiCloud

# fast build rule for target.
AperiCloud/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/AperiCloud.dir/build.make src/CBinaires/CMakeFiles/AperiCloud.dir/build
.PHONY : AperiCloud/fast

#=============================================================================
# Target rules for targets named Digeo

# Build rule for target.
Digeo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Digeo
.PHONY : Digeo

# fast build rule for target.
Digeo/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Digeo.dir/build.make src/CBinaires/CMakeFiles/Digeo.dir/build
.PHONY : Digeo/fast

#=============================================================================
# Target rules for targets named Apero

# Build rule for target.
Apero: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Apero
.PHONY : Apero

# fast build rule for target.
Apero/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Apero.dir/build.make src/CBinaires/CMakeFiles/Apero.dir/build
.PHONY : Apero/fast

#=============================================================================
# Target rules for targets named Apero2PMVS

# Build rule for target.
Apero2PMVS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Apero2PMVS
.PHONY : Apero2PMVS

# fast build rule for target.
Apero2PMVS/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Apero2PMVS.dir/build.make src/CBinaires/CMakeFiles/Apero2PMVS.dir/build
.PHONY : Apero2PMVS/fast

#=============================================================================
# Target rules for targets named mmxv

# Build rule for target.
mmxv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mmxv
.PHONY : mmxv

# fast build rule for target.
mmxv/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/mmxv.dir/build.make src/CBinaires/CMakeFiles/mmxv.dir/build
.PHONY : mmxv/fast

#=============================================================================
# Target rules for targets named Bascule

# Build rule for target.
Bascule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Bascule
.PHONY : Bascule

# fast build rule for target.
Bascule/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Bascule.dir/build.make src/CBinaires/CMakeFiles/Bascule.dir/build
.PHONY : Bascule/fast

#=============================================================================
# Target rules for targets named BatchFDC

# Build rule for target.
BatchFDC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BatchFDC
.PHONY : BatchFDC

# fast build rule for target.
BatchFDC/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/BatchFDC.dir/build.make src/CBinaires/CMakeFiles/BatchFDC.dir/build
.PHONY : BatchFDC/fast

#=============================================================================
# Target rules for targets named CmpCalib

# Build rule for target.
CmpCalib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CmpCalib
.PHONY : CmpCalib

# fast build rule for target.
CmpCalib/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/CmpCalib.dir/build.make src/CBinaires/CMakeFiles/CmpCalib.dir/build
.PHONY : CmpCalib/fast

#=============================================================================
# Target rules for targets named Dequant

# Build rule for target.
Dequant: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Dequant
.PHONY : Dequant

# fast build rule for target.
Dequant/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Dequant.dir/build.make src/CBinaires/CMakeFiles/Dequant.dir/build
.PHONY : Dequant/fast

#=============================================================================
# Target rules for targets named vic

# Build rule for target.
vic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vic
.PHONY : vic

# fast build rule for target.
vic/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/vic.dir/build.make src/CBinaires/CMakeFiles/vic.dir/build
.PHONY : vic/fast

#=============================================================================
# Target rules for targets named Devlop

# Build rule for target.
Devlop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Devlop
.PHONY : Devlop

# fast build rule for target.
Devlop/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Devlop.dir/build.make src/CBinaires/CMakeFiles/Devlop.dir/build
.PHONY : Devlop/fast

#=============================================================================
# Target rules for targets named Drunk

# Build rule for target.
Drunk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Drunk
.PHONY : Drunk

# fast build rule for target.
Drunk/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Drunk.dir/build.make src/CBinaires/CMakeFiles/Drunk.dir/build
.PHONY : Drunk/fast

#=============================================================================
# Target rules for targets named ElDcraw

# Build rule for target.
ElDcraw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ElDcraw
.PHONY : ElDcraw

# fast build rule for target.
ElDcraw/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/ElDcraw.dir/build.make src/CBinaires/CMakeFiles/ElDcraw.dir/build
.PHONY : ElDcraw/fast

#=============================================================================
# Target rules for targets named GCPBascule

# Build rule for target.
GCPBascule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GCPBascule
.PHONY : GCPBascule

# fast build rule for target.
GCPBascule/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/GCPBascule.dir/build.make src/CBinaires/CMakeFiles/GCPBascule.dir/build
.PHONY : GCPBascule/fast

#=============================================================================
# Target rules for targets named CenterBascule

# Build rule for target.
CenterBascule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CenterBascule
.PHONY : CenterBascule

# fast build rule for target.
CenterBascule/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/CenterBascule.dir/build.make src/CBinaires/CMakeFiles/CenterBascule.dir/build
.PHONY : CenterBascule/fast

#=============================================================================
# Target rules for targets named GIMMI

# Build rule for target.
GIMMI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GIMMI
.PHONY : GIMMI

# fast build rule for target.
GIMMI/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/GIMMI.dir/build.make src/CBinaires/CMakeFiles/GIMMI.dir/build
.PHONY : GIMMI/fast

#=============================================================================
# Target rules for targets named GenXML2Cpp

# Build rule for target.
GenXML2Cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GenXML2Cpp
.PHONY : GenXML2Cpp

# fast build rule for target.
GenXML2Cpp/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/GenXML2Cpp.dir/build.make src/CBinaires/CMakeFiles/GenXML2Cpp.dir/build
.PHONY : GenXML2Cpp/fast

#=============================================================================
# Target rules for targets named Gri2Bin

# Build rule for target.
Gri2Bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Gri2Bin
.PHONY : Gri2Bin

# fast build rule for target.
Gri2Bin/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Gri2Bin.dir/build.make src/CBinaires/CMakeFiles/Gri2Bin.dir/build
.PHONY : Gri2Bin/fast

#=============================================================================
# Target rules for targets named GrShade

# Build rule for target.
GrShade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GrShade
.PHONY : GrShade

# fast build rule for target.
GrShade/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/GrShade.dir/build.make src/CBinaires/CMakeFiles/GrShade.dir/build
.PHONY : GrShade/fast

#=============================================================================
# Target rules for targets named MakeGrid

# Build rule for target.
MakeGrid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MakeGrid
.PHONY : MakeGrid

# fast build rule for target.
MakeGrid/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/MakeGrid.dir/build.make src/CBinaires/CMakeFiles/MakeGrid.dir/build
.PHONY : MakeGrid/fast

#=============================================================================
# Target rules for targets named Malt

# Build rule for target.
Malt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Malt
.PHONY : Malt

# fast build rule for target.
Malt/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Malt.dir/build.make src/CBinaires/CMakeFiles/Malt.dir/build
.PHONY : Malt/fast

#=============================================================================
# Target rules for targets named MapCmd

# Build rule for target.
MapCmd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MapCmd
.PHONY : MapCmd

# fast build rule for target.
MapCmd/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/MapCmd.dir/build.make src/CBinaires/CMakeFiles/MapCmd.dir/build
.PHONY : MapCmd/fast

#=============================================================================
# Target rules for targets named MICMAC

# Build rule for target.
MICMAC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MICMAC
.PHONY : MICMAC

# fast build rule for target.
MICMAC/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/MICMAC.dir/build.make src/CBinaires/CMakeFiles/MICMAC.dir/build
.PHONY : MICMAC/fast

#=============================================================================
# Target rules for targets named MpDcraw

# Build rule for target.
MpDcraw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MpDcraw
.PHONY : MpDcraw

# fast build rule for target.
MpDcraw/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/MpDcraw.dir/build.make src/CBinaires/CMakeFiles/MpDcraw.dir/build
.PHONY : MpDcraw/fast

#=============================================================================
# Target rules for targets named Nuage2Ply

# Build rule for target.
Nuage2Ply: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nuage2Ply
.PHONY : Nuage2Ply

# fast build rule for target.
Nuage2Ply/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Nuage2Ply.dir/build.make src/CBinaires/CMakeFiles/Nuage2Ply.dir/build
.PHONY : Nuage2Ply/fast

#=============================================================================
# Target rules for targets named Pasta

# Build rule for target.
Pasta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pasta
.PHONY : Pasta

# fast build rule for target.
Pasta/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Pasta.dir/build.make src/CBinaires/CMakeFiles/Pasta.dir/build
.PHONY : Pasta/fast

#=============================================================================
# Target rules for targets named PastDevlop

# Build rule for target.
PastDevlop: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PastDevlop
.PHONY : PastDevlop

# fast build rule for target.
PastDevlop/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/PastDevlop.dir/build.make src/CBinaires/CMakeFiles/PastDevlop.dir/build
.PHONY : PastDevlop/fast

#=============================================================================
# Target rules for targets named Pastis

# Build rule for target.
Pastis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pastis
.PHONY : Pastis

# fast build rule for target.
Pastis/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Pastis.dir/build.make src/CBinaires/CMakeFiles/Pastis.dir/build
.PHONY : Pastis/fast

#=============================================================================
# Target rules for targets named Porto

# Build rule for target.
Porto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Porto
.PHONY : Porto

# fast build rule for target.
Porto/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Porto.dir/build.make src/CBinaires/CMakeFiles/Porto.dir/build
.PHONY : Porto/fast

#=============================================================================
# Target rules for targets named Reduc2MM

# Build rule for target.
Reduc2MM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Reduc2MM
.PHONY : Reduc2MM

# fast build rule for target.
Reduc2MM/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Reduc2MM.dir/build.make src/CBinaires/CMakeFiles/Reduc2MM.dir/build
.PHONY : Reduc2MM/fast

#=============================================================================
# Target rules for targets named ReducHom

# Build rule for target.
ReducHom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ReducHom
.PHONY : ReducHom

# fast build rule for target.
ReducHom/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/ReducHom.dir/build.make src/CBinaires/CMakeFiles/ReducHom.dir/build
.PHONY : ReducHom/fast

#=============================================================================
# Target rules for targets named RepLocBascule

# Build rule for target.
RepLocBascule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RepLocBascule
.PHONY : RepLocBascule

# fast build rule for target.
RepLocBascule/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/RepLocBascule.dir/build.make src/CBinaires/CMakeFiles/RepLocBascule.dir/build
.PHONY : RepLocBascule/fast

#=============================================================================
# Target rules for targets named SBGlobBascule

# Build rule for target.
SBGlobBascule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SBGlobBascule
.PHONY : SBGlobBascule

# fast build rule for target.
SBGlobBascule/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SBGlobBascule.dir/build.make src/CBinaires/CMakeFiles/SBGlobBascule.dir/build
.PHONY : SBGlobBascule/fast

#=============================================================================
# Target rules for targets named ScaleIm

# Build rule for target.
ScaleIm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ScaleIm
.PHONY : ScaleIm

# fast build rule for target.
ScaleIm/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/ScaleIm.dir/build.make src/CBinaires/CMakeFiles/ScaleIm.dir/build
.PHONY : ScaleIm/fast

#=============================================================================
# Target rules for targets named ScaleNuage

# Build rule for target.
ScaleNuage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ScaleNuage
.PHONY : ScaleNuage

# fast build rule for target.
ScaleNuage/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/ScaleNuage.dir/build.make src/CBinaires/CMakeFiles/ScaleNuage.dir/build
.PHONY : ScaleNuage/fast

#=============================================================================
# Target rules for targets named SysCoordPolyn

# Build rule for target.
SysCoordPolyn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SysCoordPolyn
.PHONY : SysCoordPolyn

# fast build rule for target.
SysCoordPolyn/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SysCoordPolyn.dir/build.make src/CBinaires/CMakeFiles/SysCoordPolyn.dir/build
.PHONY : SysCoordPolyn/fast

#=============================================================================
# Target rules for targets named Tapas

# Build rule for target.
Tapas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tapas
.PHONY : Tapas

# fast build rule for target.
Tapas/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Tapas.dir/build.make src/CBinaires/CMakeFiles/Tapas.dir/build
.PHONY : Tapas/fast

#=============================================================================
# Target rules for targets named Campari

# Build rule for target.
Campari: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Campari
.PHONY : Campari

# fast build rule for target.
Campari/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Campari.dir/build.make src/CBinaires/CMakeFiles/Campari.dir/build
.PHONY : Campari/fast

#=============================================================================
# Target rules for targets named Tapioca

# Build rule for target.
Tapioca: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tapioca
.PHONY : Tapioca

# fast build rule for target.
Tapioca/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Tapioca.dir/build.make src/CBinaires/CMakeFiles/Tapioca.dir/build
.PHONY : Tapioca/fast

#=============================================================================
# Target rules for targets named Tarama

# Build rule for target.
Tarama: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tarama
.PHONY : Tarama

# fast build rule for target.
Tarama/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Tarama.dir/build.make src/CBinaires/CMakeFiles/Tarama.dir/build
.PHONY : Tarama/fast

#=============================================================================
# Target rules for targets named Tawny

# Build rule for target.
Tawny: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tawny
.PHONY : Tawny

# fast build rule for target.
Tawny/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Tawny.dir/build.make src/CBinaires/CMakeFiles/Tawny.dir/build
.PHONY : Tawny/fast

#=============================================================================
# Target rules for targets named TestCam

# Build rule for target.
TestCam: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCam
.PHONY : TestCam

# fast build rule for target.
TestCam/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/TestCam.dir/build.make src/CBinaires/CMakeFiles/TestCam.dir/build
.PHONY : TestCam/fast

#=============================================================================
# Target rules for targets named TestCmds

# Build rule for target.
TestCmds: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TestCmds
.PHONY : TestCmds

# fast build rule for target.
TestCmds/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/TestCmds.dir/build.make src/CBinaires/CMakeFiles/TestCmds.dir/build
.PHONY : TestCmds/fast

#=============================================================================
# Target rules for targets named tiff_info

# Build rule for target.
tiff_info: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tiff_info
.PHONY : tiff_info

# fast build rule for target.
tiff_info/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/tiff_info.dir/build.make src/CBinaires/CMakeFiles/tiff_info.dir/build
.PHONY : tiff_info/fast

#=============================================================================
# Target rules for targets named to8Bits

# Build rule for target.
to8Bits: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 to8Bits
.PHONY : to8Bits

# fast build rule for target.
to8Bits/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/to8Bits.dir/build.make src/CBinaires/CMakeFiles/to8Bits.dir/build
.PHONY : to8Bits/fast

#=============================================================================
# Target rules for targets named Vino

# Build rule for target.
Vino: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vino
.PHONY : Vino

# fast build rule for target.
Vino/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/Vino.dir/build.make src/CBinaires/CMakeFiles/Vino.dir/build
.PHONY : Vino/fast

#=============================================================================
# Target rules for targets named SaisieAppuisInit

# Build rule for target.
SaisieAppuisInit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SaisieAppuisInit
.PHONY : SaisieAppuisInit

# fast build rule for target.
SaisieAppuisInit/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SaisieAppuisInit.dir/build.make src/CBinaires/CMakeFiles/SaisieAppuisInit.dir/build
.PHONY : SaisieAppuisInit/fast

#=============================================================================
# Target rules for targets named SaisieAppuisPredic

# Build rule for target.
SaisieAppuisPredic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SaisieAppuisPredic
.PHONY : SaisieAppuisPredic

# fast build rule for target.
SaisieAppuisPredic/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SaisieAppuisPredic.dir/build.make src/CBinaires/CMakeFiles/SaisieAppuisPredic.dir/build
.PHONY : SaisieAppuisPredic/fast

#=============================================================================
# Target rules for targets named SaisieBasc

# Build rule for target.
SaisieBasc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SaisieBasc
.PHONY : SaisieBasc

# fast build rule for target.
SaisieBasc/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SaisieBasc.dir/build.make src/CBinaires/CMakeFiles/SaisieBasc.dir/build
.PHONY : SaisieBasc/fast

#=============================================================================
# Target rules for targets named SaisieMasq

# Build rule for target.
SaisieMasq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SaisieMasq
.PHONY : SaisieMasq

# fast build rule for target.
SaisieMasq/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SaisieMasq.dir/build.make src/CBinaires/CMakeFiles/SaisieMasq.dir/build
.PHONY : SaisieMasq/fast

#=============================================================================
# Target rules for targets named SaisiePts

# Build rule for target.
SaisiePts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SaisiePts
.PHONY : SaisiePts

# fast build rule for target.
SaisiePts/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SaisiePts.dir/build.make src/CBinaires/CMakeFiles/SaisiePts.dir/build
.PHONY : SaisiePts/fast

#=============================================================================
# Target rules for targets named SEL

# Build rule for target.
SEL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SEL
.PHONY : SEL

# fast build rule for target.
SEL/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/SEL.dir/build.make src/CBinaires/CMakeFiles/SEL.dir/build
.PHONY : SEL/fast

#=============================================================================
# Target rules for targets named EPExeCompens

# Build rule for target.
EPExeCompens: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExeCompens
.PHONY : EPExeCompens

# fast build rule for target.
EPExeCompens/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExeCompens.dir/build.make src/CBinaires/CMakeFiles/EPExeCompens.dir/build
.PHONY : EPExeCompens/fast

#=============================================================================
# Target rules for targets named ScriptCalib

# Build rule for target.
ScriptCalib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ScriptCalib
.PHONY : ScriptCalib

# fast build rule for target.
ScriptCalib/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/ScriptCalib.dir/build.make src/CBinaires/CMakeFiles/ScriptCalib.dir/build
.PHONY : ScriptCalib/fast

#=============================================================================
# Target rules for targets named EPExeCatImSaisie

# Build rule for target.
EPExeCatImSaisie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExeCatImSaisie
.PHONY : EPExeCatImSaisie

# fast build rule for target.
EPExeCatImSaisie/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExeCatImSaisie.dir/build.make src/CBinaires/CMakeFiles/EPExeCatImSaisie.dir/build
.PHONY : EPExeCatImSaisie/fast

#=============================================================================
# Target rules for targets named EPExeCalibFinale

# Build rule for target.
EPExeCalibFinale: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExeCalibFinale
.PHONY : EPExeCalibFinale

# fast build rule for target.
EPExeCalibFinale/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExeCalibFinale.dir/build.make src/CBinaires/CMakeFiles/EPExeCalibFinale.dir/build
.PHONY : EPExeCalibFinale/fast

#=============================================================================
# Target rules for targets named EPExeCalibInit

# Build rule for target.
EPExeCalibInit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExeCalibInit
.PHONY : EPExeCalibInit

# fast build rule for target.
EPExeCalibInit/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExeCalibInit.dir/build.make src/CBinaires/CMakeFiles/EPExeCalibInit.dir/build
.PHONY : EPExeCalibInit/fast

#=============================================================================
# Target rules for targets named EPExeConvertPolygone

# Build rule for target.
EPExeConvertPolygone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExeConvertPolygone
.PHONY : EPExeConvertPolygone

# fast build rule for target.
EPExeConvertPolygone/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExeConvertPolygone.dir/build.make src/CBinaires/CMakeFiles/EPExeConvertPolygone.dir/build
.PHONY : EPExeConvertPolygone/fast

#=============================================================================
# Target rules for targets named EPExePointeInitPolyg

# Build rule for target.
EPExePointeInitPolyg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExePointeInitPolyg
.PHONY : EPExePointeInitPolyg

# fast build rule for target.
EPExePointeInitPolyg/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExePointeInitPolyg.dir/build.make src/CBinaires/CMakeFiles/EPExePointeInitPolyg.dir/build
.PHONY : EPExePointeInitPolyg/fast

#=============================================================================
# Target rules for targets named EPExeRechCibleDRad

# Build rule for target.
EPExeRechCibleDRad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExeRechCibleDRad
.PHONY : EPExeRechCibleDRad

# fast build rule for target.
EPExeRechCibleDRad/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExeRechCibleDRad.dir/build.make src/CBinaires/CMakeFiles/EPExeRechCibleDRad.dir/build
.PHONY : EPExeRechCibleDRad/fast

#=============================================================================
# Target rules for targets named EPExeRechCibleInit

# Build rule for target.
EPExeRechCibleInit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EPExeRechCibleInit
.PHONY : EPExeRechCibleInit

# fast build rule for target.
EPExeRechCibleInit/fast:
	$(MAKE) $(MAKESILENT) -f src/CBinaires/CMakeFiles/EPExeRechCibleInit.dir/build.make src/CBinaires/CMakeFiles/EPExeRechCibleInit.dir/build
.PHONY : EPExeRechCibleInit/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... elise_"
	@echo "... ANN"
	@echo "... AperiCloud"
	@echo "... Apero"
	@echo "... Apero2PMVS"
	@echo "... Bascule"
	@echo "... BatchFDC"
	@echo "... Campari"
	@echo "... CenterBascule"
	@echo "... CmpCalib"
	@echo "... Dequant"
	@echo "... Devlop"
	@echo "... Digeo"
	@echo "... Drunk"
	@echo "... EPExeCalibFinale"
	@echo "... EPExeCalibInit"
	@echo "... EPExeCatImSaisie"
	@echo "... EPExeCompens"
	@echo "... EPExeConvertPolygone"
	@echo "... EPExePointeInitPolyg"
	@echo "... EPExeRechCibleDRad"
	@echo "... EPExeRechCibleInit"
	@echo "... ElDcraw"
	@echo "... GCPBascule"
	@echo "... GIMMI"
	@echo "... GenXML2Cpp"
	@echo "... GrShade"
	@echo "... Gri2Bin"
	@echo "... MICMAC"
	@echo "... MakeGrid"
	@echo "... Malt"
	@echo "... MapCmd"
	@echo "... MpDcraw"
	@echo "... Nuage2Ply"
	@echo "... PastDevlop"
	@echo "... Pasta"
	@echo "... Pastis"
	@echo "... PoissonRecon"
	@echo "... Porto"
	@echo "... Reduc2MM"
	@echo "... ReducHom"
	@echo "... RepLocBascule"
	@echo "... SBGlobBascule"
	@echo "... SEL"
	@echo "... SaisieAppuisInit"
	@echo "... SaisieAppuisPredic"
	@echo "... SaisieBasc"
	@echo "... SaisieMasq"
	@echo "... SaisiePts"
	@echo "... ScaleIm"
	@echo "... ScaleNuage"
	@echo "... ScriptCalib"
	@echo "... SurfaceTrimmer"
	@echo "... SysCoordPolyn"
	@echo "... Tapas"
	@echo "... Tapioca"
	@echo "... Tarama"
	@echo "... Tawny"
	@echo "... TestCam"
	@echo "... TestCmds"
	@echo "... Vino"
	@echo "... elise"
	@echo "... mm3d"
	@echo "... mmxv"
	@echo "... poisson"
	@echo "... tiff_info"
	@echo "... to8Bits"
	@echo "... vic"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

